################################iCAMP#####################################

rm(list=ls())
t0=Sys.time() # to calculate time cost

# 1 # set folder paths and file names, please change according to the folder paths and file names in your computer.
# the folder saving the input files
wd="E:/Saline-alkali soil/Saline-alkali/amplicon/result-U/Protist/otu/iCAMP2/input/"

# the OTU table file (Tab delimited txt file)
com.file="otu_protistFlattening.csv"

# the phylogenetic tree file
tree.file="prot_sequence.nwk"

# the classification (taxonomy) information
clas.file="HMME.prot.OTU.ID1.csv"

# the treatment informaiton table
treat.file="group.amf1.OTU.csv"

# the environmental varialbes
env.file="sample_metadata.csv"
# if you do not have env file or the env may not represent niche, skip step 7 and 8, but check the alternative way to determine binning setting, e.g. bin.size.limit.

# the folder to save the output. please change to a new folder even if you are just testing the example data.
save.wd="E:/Saline-alkali soil/Saline-alkali/amplicon/result-U/Protist/otu/iCAMP2/output1/"
if(!dir.exists(save.wd)){dir.create(save.wd)}

# 2 # key parameter setting
prefix="Protist"  # prefix of the output file names. usually use a project ID.
rand.time=100  # randomization time, 1000 is usually enough. For example test, you may set as 100 or less to save time.
nworker=10 # nworker is thread number for parallel computing, which depends on the CPU core number of your computer.
memory.G=4 # to set the memory size as you need (but should be less than the available space in your hard disk), so that calculation of large tree will not be limited by physical memory. unit is Gb.

# 3 # load R packages and data
library(iCAMP)
library(ape)
setwd(wd)
comm=t(read.csv(com.file, header = TRUE, row.names = 1,
                as.is = TRUE, stringsAsFactors = FALSE, comment.char = "",
                check.names = FALSE))
tree=read.tree(file = tree.file)
clas=read.csv(clas.file, header = TRUE,  row.names = 1,
              as.is = TRUE, stringsAsFactors = FALSE, comment.char = "",
              check.names = FALSE)
treat=read.csv(treat.file, header = TRUE,  row.names = 1,
               as.is = TRUE, stringsAsFactors = FALSE, comment.char = "",
               check.names = FALSE)

env=read.csv(env.file, header = TRUE,  row.names = 1,
             as.is = TRUE, stringsAsFactors = FALSE, comment.char = "",
             check.names = FALSE) # skip this if you do not have env.file
env <- env[,8:13]

# 4 # match sample IDs in OTU table and treatment information table
sampid.check=match.name(rn.list=list(comm=comm,treat=treat,env=env))
# sampid.check=match.name(rn.list=list(comm=comm,treat=treat)) # if you do not have env.file
# for the example data, the output should be "All match very well".
# for your data files, if you have not matched their IDs, the unmatched samples will be removed.
treat=sampid.check$treat
comm=sampid.check$comm
comm=comm[,colSums(comm)>0,drop=FALSE] # if some unmatched samples were removed, some OTUs may become ghosts, then you may use this line to remove them if necessary.
env=sampid.check$env # skip this if you do not have env.file

# 5 # match OTU IDs in OTU table and tree file
spid.check=match.name(cn.list=list(comm=comm),rn.list=list(clas=clas),tree.list=list(tree=tree))
# for the example data, the output should be "All match very well".
# for your data files, if you have not matched the IDs before, the unmatched OTUs will be removed.
comm=spid.check$comm
clas=spid.check$clas
tree=spid.check$tree

# 6 # calculate pairwise phylogenetic distance matrix.
# since microbial community data usually has a large number of species (OTUs or ASVs), we use "big.matrix" in R package "bigmemory" to handle the large phylogenetic distance matrix. 
setwd(save.wd)
if(!file.exists("pd.desc")) {
  pd.big=iCAMP::pdist.big(tree = tree, wd=save.wd, nworker = nworker, memory.G = memory.G)
  # output files:
  # path.rda: a R object to list all the nodes and  edge lengthes from root to every tip. saved in R data format. an intermediate output when claculating phylogenetic distance matrix.
  # pd.bin: BIN file (backingfile) generated by function big.matrix in R package bigmemory. This is the big matrix storing pairwise phylogenetic distance values. By using this bigmemory format file, we will not need memory but hard disk when calling big matrix for calculation.
  # pd.desc: the DESC file (descriptorfile) to hold the backingfile (pd.bin) description.
  # pd.taxon.name.csv: comma delimited csv file storing the IDs of tree tips (OTUs), serving as the row/column names of the big phylogenetic distance matrix.
}else{
  # if you already calculated the phylogenetic distance matrix in a previous run
  pd.big=list()
  pd.big$tip.label=read.csv(paste0(save.wd,"/pd.taxon.name.csv"),row.names = 1,stringsAsFactors = FALSE)[,1]
  pd.big$pd.wd=save.wd
  pd.big$pd.file="pd.desc"
  pd.big$pd.name.file="pd.taxon.name.csv"
}

####################
# 9 # iCAMP analysis
# 9.1 # without omitting small bins.
# commonly use # set sig.index as Confidence instead of SES.RC (betaNRI/NTI + RCbray)
# bin.size.limit = 168 # For real data, usually use a proper number according to phylogenetic signal test or try some settings then choose the reasonable stochasticity level. our experience is 12, or 24, or 48. but for this example dataset which is too small, have to use 5.
# ds = 0.2 
my_icamp <- function(bin.size.limit,ds){
  sig.index="Confidence" # see other options in help document of icamp.big.
  icres=iCAMP::icamp.big(comm=comm, pd.desc = pd.big$pd.file, pd.spname=pd.big$tip.label,
                         pd.wd = pd.big$pd.wd, rand = rand.time, tree=tree,
                         prefix = prefix, ds = ds, pd.cut = NA, sp.check = TRUE,
                         phylo.rand.scale = "within.bin", taxa.rand.scale = "across.all",
                         phylo.metric = "bMPD", sig.index=sig.index, bin.size.limit = bin.size.limit, 
                         nworker = nworker, memory.G = memory.G, rtree.save = FALSE, detail.save = TRUE, 
                         qp.save = FALSE, detail.null = FALSE, ignore.zero = TRUE, output.wd = save.wd, 
                         correct.special = TRUE, unit.sum = rowSums(comm), special.method = "depend",
                         ses.cut = 1.96, rc.cut = 0.95, conf.cut=0.975, omit.option = "no",meta.ab = NULL)
  # there are quite a few parameters in this function, please check the help document of "icamp.big".
  # output files:
  # Test.iCAMP.detail.rda: the object "icres" saved in R data format. it is a list object. The first element bNRIiRCa is the result of relative importance of each assembly process in each pairwise comparison (each turnover). The second element "detail" including binning information (named taxabin), phylogenetic and taxonomic metrics results in each bin (named like bNRIi, RCa, etc.), relative abundance of each bin (bin.weight), relative importance of each process in each turnover between communities (processes), input settings (setting), and input community data matrix (comm). See help document of the function icamp.big for more details.
  
  ###############################
  # 10 # iCAMP bin level statistics
  icbin=iCAMP::icamp.bins(icamp.detail = icres$detail,treat = treat,
                          clas=clas,silent=FALSE, boot = TRUE,
                          rand.time = rand.time,between.group = TRUE)
  save(icbin,file = paste0(prefix,"-",bin.size.limit,"-",ds,".iCAMP.Summary.rda")) # just to archive the result. rda file is automatically compressed, and easy to load into R.
  
  if(file.exists(paste0(prefix,".ProcessImportance_EachGroup.csv"))){appendy=TRUE;col.namesy=FALSE}else{appendy=FALSE;col.namesy=TRUE}
  write.table(data.frame(ds=ds,n.min=bin.size.limit,icbin$Pt),
              file = paste0(prefix,".ProcessImportance_EachGroup.csv"),
              append = appendy, quote=FALSE, sep=",", row.names = FALSE,col.names = col.namesy)
  
  if(file.exists(paste0(prefix,".ProcessImportance_EachBin_EachGroup.csv"))){appendy=TRUE;col.namesy2=FALSE}else{appendy=FALSE;col.namesy2=TRUE}
  write.table(data.frame(ds=ds,n.min=bin.size.limit,icbin$Ptk),
              file = paste0(prefix,".ProcessImportance_EachBin_EachGroup.csv"),
              append = appendy, quote=FALSE, sep=",", row.names = FALSE,col.names = col.namesy2)
  
  if(file.exists(paste0(prefix,".ProcessImportance_EachTurnover.csv"))){appendy=TRUE;col.namesy3=FALSE}else{appendy=FALSE;col.namesy3=TRUE}
  write.table(data.frame(ds=ds,n.min=bin.size.limit,icbin$Ptuv),
              file = paste0(prefix,".ProcessImportance_EachTurnover.csv"),
              append = appendy, quote=FALSE, sep=",", row.names = FALSE,col.names = col.namesy3)
  
  if(file.exists(paste0(prefix,".BinContributeToProcess_EachGroup.csv"))){appendy=TRUE;col.namesy4=FALSE}else{appendy=FALSE;col.namesy4=TRUE}
  write.table(data.frame(ds=ds,n.min=bin.size.limit,icbin$BPtk),
              file = paste0(prefix,".BinContributeToProcess_EachGroup.csv"),
              append = appendy, quote=FALSE, sep=",", row.names = FALSE,col.names = col.namesy4)
  
  if(file.exists(paste0(prefix,".Taxon_Bin.csv"))){appendy=TRUE;col.namesy5=FALSE}else{appendy=FALSE;col.namesy5=TRUE}
  write.table(data.frame(ds=ds,n.min=bin.size.limit,ID=rownames(icbin$Class.Bin),icbin$Class.Bin,stringsAsFactors = FALSE),
              file = paste0(prefix,".Taxon_Bin.csv"),
              append = appendy, quote=FALSE, sep=",", row.names = FALSE,col.names = col.namesy5)
  
  if(file.exists(paste0(prefix,".Bin_TopTaxon.csv"))){appendy=TRUE;col.namesy6=FALSE}else{appendy=FALSE;col.namesy6=TRUE}
  write.table(data.frame(ds=ds,n.min=bin.size.limit,icbin$Bin.TopClass),
              file = paste0(prefix,".Bin_TopTaxon.csv"),
              append = appendy, quote=FALSE, sep=",", row.names = FALSE,col.names = col.namesy6)
  
  # output files:
  # Test.iCAMP.Summary.rda: the object "icbin" saved in R data format. see help document of the function icamp.bins for description of each element in the object.
  # Test.ProcessImportance_EachGroup.csv: Relative importance of each process in governing the turnovers in a group of samples.
  # Test.ProcessImportance_EachBin_EachGroup.csv: Relative importance of each process in governing the turnovers of each bin among a group of samples.
  # Test.ProcessImportance_EachTurnover.csv: Relative importance of each process in governing the turnovers between each pair of communities (samples).
  # Test.BinContributeToProcess_EachGroup.csv: Bin contribution to each process, measuring the contribution of each bin to the relative importance of each process in the assembly of a group of communities.
  # Test.Taxon_Bin.csv: a matrix showing the bin ID and classification information for each taxon.
  # Test.Bin_TopTaxon.csv: a matrix showing the bin relative abundance; the top taxon ID, percentage in bin, and classification; the most abundant name at each phylogeny level in the bin.
  
  # 11 # Bootstrapping test
  # please specify which column in the treatment information table.
  i=1
  treat.use=treat[,i,drop=FALSE]
  icamp.result=icres$CbMPDiCBraya
  icboot=iCAMP::icamp.boot(icamp.result = icamp.result,treat = treat.use,rand.time = rand.time,
                           compare = TRUE,silent = FALSE,between.group = TRUE,ST.estimation = TRUE)
  save(icboot,file=paste0(prefix,"-",bin.size.limit,"-",ds,".iCAMP.Boot.",colnames(treat)[i],".rda"))
  
  if(file.exists(paste0(prefix,".iCAMP.BootSummary.",colnames(treat)[i],".csv"))){appendy=TRUE;col.namesy7=FALSE}else{appendy=FALSE;col.namesy7=TRUE}
  write.table(data.frame(ds=ds,n.min=bin.size.limit,icboot$summary),file = paste0(prefix,".iCAMP.BootSummary.",colnames(treat)[i],".csv"),
              append = appendy, quote=FALSE, sep=",", row.names = FALSE,col.names = col.namesy7)
  
  if(file.exists(paste0(prefix,".iCAMP.Compare.",colnames(treat)[i],".csv"))){appendy=TRUE;col.namesy8=FALSE}else{appendy=FALSE;col.namesy8=TRUE}
  write.table(data.frame(ds=ds,n.min=bin.size.limit,icboot$compare),file = paste0(prefix,".iCAMP.Compare.",colnames(treat)[i],".csv"),
              append = appendy, quote=FALSE, sep=",", row.names = FALSE,col.names = col.namesy8)
}
# output files:
# Test.iCAMP.Boot.Management.rda: the object "icboot" saved in R data format. see help document of the function icamp.boot for description of each element in the object.
# Test.BootSummary.Management.csv: a table to summarize bootstrapping results. see help document of the function icamp.boot for description of the output element "summary".
# Test.Compare.Management.csv: a table to summarize comparison index, effect size, and significance between each two groups. see help document of the function icamp.boot for description of the output element "compare".
for (bin in seq(96)){
  for (d in seq(0.2)){
    my_icamp(bin,d)}}

my_icamp(96,0.2)
